// <auto-generated />
namespace SwissTransport.UI.Forms
{
    partial class SwissTransportMainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(SwissTransportMainForm));
            this.tabControl = new System.Windows.Forms.TabControl();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.btSearchConnections = new System.Windows.Forms.Button();
            this.gbExtendedOptions = new System.Windows.Forms.GroupBox();
            this.dtpConnectionSearchTime = new System.Windows.Forms.DateTimePicker();
            this.rbArrivalTime = new System.Windows.Forms.RadioButton();
            this.rbDepartureTime = new System.Windows.Forms.RadioButton();
            this.label5 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.dtpConnectionSearchDate = new System.Windows.Forms.DateTimePicker();
            this.cbShowExtendedOptions = new System.Windows.Forms.CheckBox();
            this.lvConnections = new System.Windows.Forms.ListView();
            this.columnHeader1 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader2 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader3 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader4 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader5 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader13 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.btSelectArrivalStation = new System.Windows.Forms.Button();
            this.btSelectDepartureStation = new System.Windows.Forms.Button();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.cbArrival = new System.Windows.Forms.ComboBox();
            this.cbDeparture = new System.Windows.Forms.ComboBox();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.btSelectStationBoardStation = new System.Windows.Forms.Button();
            this.cbAutoRefreshStationBoard = new System.Windows.Forms.CheckBox();
            this.gbMoreStationOptions = new System.Windows.Forms.GroupBox();
            this.label7 = new System.Windows.Forms.Label();
            this.dtpStationBoardDate = new System.Windows.Forms.DateTimePicker();
            this.label11 = new System.Windows.Forms.Label();
            this.dtpStationBoardTime = new System.Windows.Forms.DateTimePicker();
            this.cbMoreStationBoardOptions = new System.Windows.Forms.CheckBox();
            this.lvStationBoard = new System.Windows.Forms.ListView();
            this.columnHeader6 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader7 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader11 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.btSearchStationBoard = new System.Windows.Forms.Button();
            this.cbSearchStationBoard = new System.Windows.Forms.ComboBox();
            this.label6 = new System.Windows.Forms.Label();
            this.tabPage3 = new System.Windows.Forms.TabPage();
            this.cbShowStationsNear = new System.Windows.Forms.Button();
            this.tbSearchStation = new System.Windows.Forms.TextBox();
            this.groupBoxStationInformation = new System.Windows.Forms.GroupBox();
            this.wbStations = new System.Windows.Forms.WebBrowser();
            this.tbStationLatitude = new System.Windows.Forms.TextBox();
            this.tbStationLongitude = new System.Windows.Forms.TextBox();
            this.label9 = new System.Windows.Forms.Label();
            this.lvStations = new System.Windows.Forms.ListView();
            this.columnHeader12 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.btStationSearch = new System.Windows.Forms.Button();
            this.label8 = new System.Windows.Forms.Label();
            this.progressBar = new System.Windows.Forms.ProgressBar();
            this.menuStrip1 = new System.Windows.Forms.MenuStrip();
            this.fileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.mailExportToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.exportToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.btSettingsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.sMTPToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.lbSelectedTab = new System.Windows.Forms.Label();
            this.timerStationBoard = new System.Windows.Forms.Timer(this.components);
            this.tabControl.SuspendLayout();
            this.tabPage2.SuspendLayout();
            this.gbExtendedOptions.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.gbMoreStationOptions.SuspendLayout();
            this.tabPage3.SuspendLayout();
            this.groupBoxStationInformation.SuspendLayout();
            this.menuStrip1.SuspendLayout();
            this.SuspendLayout();
            // 
            // tabControl
            // 
            this.tabControl.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.tabControl.Controls.Add(this.tabPage2);
            this.tabControl.Controls.Add(this.tabPage1);
            this.tabControl.Controls.Add(this.tabPage3);
            this.tabControl.Location = new System.Drawing.Point(0, 66);
            this.tabControl.Margin = new System.Windows.Forms.Padding(2);
            this.tabControl.Name = "tabControl";
            this.tabControl.SelectedIndex = 0;
            this.tabControl.Size = new System.Drawing.Size(901, 510);
            this.tabControl.TabIndex = 0;
            this.tabControl.SelectedIndexChanged += new System.EventHandler(this.TabControl_SelectedIndexChanged);
            // 
            // tabPage2
            // 
            this.tabPage2.Controls.Add(this.btSearchConnections);
            this.tabPage2.Controls.Add(this.gbExtendedOptions);
            this.tabPage2.Controls.Add(this.cbShowExtendedOptions);
            this.tabPage2.Controls.Add(this.lvConnections);
            this.tabPage2.Controls.Add(this.groupBox1);
            this.tabPage2.Location = new System.Drawing.Point(4, 22);
            this.tabPage2.Margin = new System.Windows.Forms.Padding(2);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(2);
            this.tabPage2.Size = new System.Drawing.Size(893, 484);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "Verbindungen";
            this.tabPage2.UseVisualStyleBackColor = true;
            // 
            // btSearchConnections
            // 
            this.btSearchConnections.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.btSearchConnections.Enabled = false;
            this.btSearchConnections.Location = new System.Drawing.Point(9, 453);
            this.btSearchConnections.Margin = new System.Windows.Forms.Padding(2);
            this.btSearchConnections.Name = "btSearchConnections";
            this.btSearchConnections.Size = new System.Drawing.Size(230, 26);
            this.btSearchConnections.TabIndex = 9;
            this.btSearchConnections.Text = "Verbindungen suchen";
            this.btSearchConnections.UseVisualStyleBackColor = true;
            this.btSearchConnections.Click += new System.EventHandler(this.SearchConnections_Click);
            // 
            // gbExtendedOptions
            // 
            this.gbExtendedOptions.Controls.Add(this.dtpConnectionSearchTime);
            this.gbExtendedOptions.Controls.Add(this.rbArrivalTime);
            this.gbExtendedOptions.Controls.Add(this.rbDepartureTime);
            this.gbExtendedOptions.Controls.Add(this.label5);
            this.gbExtendedOptions.Controls.Add(this.label4);
            this.gbExtendedOptions.Controls.Add(this.label3);
            this.gbExtendedOptions.Controls.Add(this.dtpConnectionSearchDate);
            this.gbExtendedOptions.Location = new System.Drawing.Point(3, 156);
            this.gbExtendedOptions.Margin = new System.Windows.Forms.Padding(2);
            this.gbExtendedOptions.Name = "gbExtendedOptions";
            this.gbExtendedOptions.Padding = new System.Windows.Forms.Padding(2);
            this.gbExtendedOptions.Size = new System.Drawing.Size(240, 173);
            this.gbExtendedOptions.TabIndex = 3;
            this.gbExtendedOptions.TabStop = false;
            this.gbExtendedOptions.Text = "Detail-Einstellungen";
            this.gbExtendedOptions.Visible = false;
            // 
            // dtpConnectionSearchTime
            // 
            this.dtpConnectionSearchTime.CustomFormat = "HH:mm";
            this.dtpConnectionSearchTime.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.dtpConnectionSearchTime.Location = new System.Drawing.Point(6, 99);
            this.dtpConnectionSearchTime.Margin = new System.Windows.Forms.Padding(2);
            this.dtpConnectionSearchTime.Name = "dtpConnectionSearchTime";
            this.dtpConnectionSearchTime.ShowUpDown = true;
            this.dtpConnectionSearchTime.Size = new System.Drawing.Size(230, 20);
            this.dtpConnectionSearchTime.TabIndex = 6;
            // 
            // rbArrivalTime
            // 
            this.rbArrivalTime.AutoSize = true;
            this.rbArrivalTime.Location = new System.Drawing.Point(99, 146);
            this.rbArrivalTime.Margin = new System.Windows.Forms.Padding(2);
            this.rbArrivalTime.Name = "rbArrivalTime";
            this.rbArrivalTime.Size = new System.Drawing.Size(83, 17);
            this.rbArrivalTime.TabIndex = 8;
            this.rbArrivalTime.TabStop = true;
            this.rbArrivalTime.Text = "Ankunftszeit";
            this.rbArrivalTime.UseVisualStyleBackColor = true;
            // 
            // rbDepartureTime
            // 
            this.rbDepartureTime.AutoSize = true;
            this.rbDepartureTime.Checked = true;
            this.rbDepartureTime.Location = new System.Drawing.Point(6, 146);
            this.rbDepartureTime.Margin = new System.Windows.Forms.Padding(2);
            this.rbDepartureTime.Name = "rbDepartureTime";
            this.rbDepartureTime.Size = new System.Drawing.Size(80, 17);
            this.rbDepartureTime.TabIndex = 7;
            this.rbDepartureTime.TabStop = true;
            this.rbDepartureTime.Text = "Abfahrtszeit";
            this.rbDepartureTime.UseVisualStyleBackColor = true;
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(3, 125);
            this.label5.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(25, 13);
            this.label5.TabIndex = 4;
            this.label5.Text = "Typ";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(3, 77);
            this.label4.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(25, 13);
            this.label4.TabIndex = 3;
            this.label4.Text = "Zeit";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(3, 28);
            this.label3.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(38, 13);
            this.label3.TabIndex = 1;
            this.label3.Text = "Datum";
            // 
            // dtpConnectionSearchDate
            // 
            this.dtpConnectionSearchDate.Location = new System.Drawing.Point(6, 48);
            this.dtpConnectionSearchDate.Margin = new System.Windows.Forms.Padding(2);
            this.dtpConnectionSearchDate.Name = "dtpConnectionSearchDate";
            this.dtpConnectionSearchDate.Size = new System.Drawing.Size(230, 20);
            this.dtpConnectionSearchDate.TabIndex = 5;
            // 
            // cbShowExtendedOptions
            // 
            this.cbShowExtendedOptions.AutoSize = true;
            this.cbShowExtendedOptions.Location = new System.Drawing.Point(9, 135);
            this.cbShowExtendedOptions.Margin = new System.Windows.Forms.Padding(2);
            this.cbShowExtendedOptions.Name = "cbShowExtendedOptions";
            this.cbShowExtendedOptions.Size = new System.Drawing.Size(142, 17);
            this.cbShowExtendedOptions.TabIndex = 4;
            this.cbShowExtendedOptions.Text = "Mehr Optionen anzeigen";
            this.cbShowExtendedOptions.UseVisualStyleBackColor = true;
            this.cbShowExtendedOptions.CheckedChanged += new System.EventHandler(this.ShowExtendedOptions_CheckedChanged);
            // 
            // lvConnections
            // 
            this.lvConnections.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.lvConnections.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.columnHeader1,
            this.columnHeader2,
            this.columnHeader3,
            this.columnHeader4,
            this.columnHeader5,
            this.columnHeader13});
            this.lvConnections.FullRowSelect = true;
            this.lvConnections.GridLines = true;
            this.lvConnections.Location = new System.Drawing.Point(247, 3);
            this.lvConnections.Margin = new System.Windows.Forms.Padding(2);
            this.lvConnections.Name = "lvConnections";
            this.lvConnections.Size = new System.Drawing.Size(645, 476);
            this.lvConnections.TabIndex = 10;
            this.lvConnections.UseCompatibleStateImageBehavior = false;
            this.lvConnections.View = System.Windows.Forms.View.Details;
            // 
            // columnHeader1
            // 
            this.columnHeader1.Text = "Mit";
            this.columnHeader1.Width = 90;
            // 
            // columnHeader2
            // 
            this.columnHeader2.Text = "Ab";
            this.columnHeader2.Width = 110;
            // 
            // columnHeader3
            // 
            this.columnHeader3.Text = "An";
            this.columnHeader3.Width = 110;
            // 
            // columnHeader4
            // 
            this.columnHeader4.Text = "Dauer";
            this.columnHeader4.Width = 90;
            // 
            // columnHeader5
            // 
            this.columnHeader5.Text = "Abfahrts-Plattform";
            this.columnHeader5.Width = 110;
            // 
            // columnHeader13
            // 
            this.columnHeader13.Text = "Ankunfts-Plattform";
            this.columnHeader13.Width = 110;
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.btSelectArrivalStation);
            this.groupBox1.Controls.Add(this.btSelectDepartureStation);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Controls.Add(this.cbArrival);
            this.groupBox1.Controls.Add(this.cbDeparture);
            this.groupBox1.Location = new System.Drawing.Point(3, 3);
            this.groupBox1.Margin = new System.Windows.Forms.Padding(2);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Padding = new System.Windows.Forms.Padding(2);
            this.groupBox1.Size = new System.Drawing.Size(240, 128);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Informationen";
            // 
            // btSelectArrivalStation
            // 
            this.btSelectArrivalStation.BackgroundImage = global::SwissTransport.UI.Properties.Resources.SelectIcon;
            this.btSelectArrivalStation.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btSelectArrivalStation.Location = new System.Drawing.Point(215, 91);
            this.btSelectArrivalStation.Name = "btSelectArrivalStation";
            this.btSelectArrivalStation.Size = new System.Drawing.Size(21, 21);
            this.btSelectArrivalStation.TabIndex = 3;
            this.btSelectArrivalStation.UseVisualStyleBackColor = true;
            this.btSelectArrivalStation.Click += new System.EventHandler(this.SelectArrivalStation_Click);
            // 
            // btSelectDepartureStation
            // 
            this.btSelectDepartureStation.BackgroundImage = global::SwissTransport.UI.Properties.Resources.SelectIcon;
            this.btSelectDepartureStation.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btSelectDepartureStation.Location = new System.Drawing.Point(215, 39);
            this.btSelectDepartureStation.Name = "btSelectDepartureStation";
            this.btSelectDepartureStation.Size = new System.Drawing.Size(21, 21);
            this.btSelectDepartureStation.TabIndex = 1;
            this.btSelectDepartureStation.UseVisualStyleBackColor = true;
            this.btSelectDepartureStation.Click += new System.EventHandler(this.SelectDepartureStation_Click);
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(4, 76);
            this.label2.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(33, 13);
            this.label2.TabIndex = 3;
            this.label2.Text = "Nach";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(3, 24);
            this.label1.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(26, 13);
            this.label1.TabIndex = 2;
            this.label1.Text = "Von";
            // 
            // cbArrival
            // 
            this.cbArrival.FormattingEnabled = true;
            this.cbArrival.Location = new System.Drawing.Point(6, 91);
            this.cbArrival.Margin = new System.Windows.Forms.Padding(2);
            this.cbArrival.Name = "cbArrival";
            this.cbArrival.Size = new System.Drawing.Size(204, 21);
            this.cbArrival.TabIndex = 2;
            this.cbArrival.DropDown += new System.EventHandler(this.LoadStationCombobox);
            this.cbArrival.SelectedIndexChanged += new System.EventHandler(this.ConnectionButtonValidation);
            this.cbArrival.TextChanged += new System.EventHandler(this.ConnectionButtonValidation);
            this.cbArrival.Leave += new System.EventHandler(this.ConnectionStationSelectionCombobox_Leave);
            // 
            // cbDeparture
            // 
            this.cbDeparture.FormattingEnabled = true;
            this.cbDeparture.Location = new System.Drawing.Point(6, 39);
            this.cbDeparture.Margin = new System.Windows.Forms.Padding(2);
            this.cbDeparture.Name = "cbDeparture";
            this.cbDeparture.Size = new System.Drawing.Size(204, 21);
            this.cbDeparture.TabIndex = 0;
            this.cbDeparture.DropDown += new System.EventHandler(this.LoadStationCombobox);
            this.cbDeparture.SelectedIndexChanged += new System.EventHandler(this.ConnectionButtonValidation);
            this.cbDeparture.TextChanged += new System.EventHandler(this.ConnectionButtonValidation);
            this.cbDeparture.Leave += new System.EventHandler(this.ConnectionStationSelectionCombobox_Leave);
            // 
            // tabPage1
            // 
            this.tabPage1.Controls.Add(this.btSelectStationBoardStation);
            this.tabPage1.Controls.Add(this.cbAutoRefreshStationBoard);
            this.tabPage1.Controls.Add(this.gbMoreStationOptions);
            this.tabPage1.Controls.Add(this.cbMoreStationBoardOptions);
            this.tabPage1.Controls.Add(this.lvStationBoard);
            this.tabPage1.Controls.Add(this.btSearchStationBoard);
            this.tabPage1.Controls.Add(this.cbSearchStationBoard);
            this.tabPage1.Controls.Add(this.label6);
            this.tabPage1.Location = new System.Drawing.Point(4, 22);
            this.tabPage1.Margin = new System.Windows.Forms.Padding(2);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(2);
            this.tabPage1.Size = new System.Drawing.Size(893, 484);
            this.tabPage1.TabIndex = 2;
            this.tabPage1.Text = "Abfahrtstafel";
            this.tabPage1.UseVisualStyleBackColor = true;
            // 
            // btSelectStationBoardStation
            // 
            this.btSelectStationBoardStation.BackgroundImage = global::SwissTransport.UI.Properties.Resources.SelectIcon;
            this.btSelectStationBoardStation.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btSelectStationBoardStation.Location = new System.Drawing.Point(219, 28);
            this.btSelectStationBoardStation.Name = "btSelectStationBoardStation";
            this.btSelectStationBoardStation.Size = new System.Drawing.Size(21, 21);
            this.btSelectStationBoardStation.TabIndex = 1;
            this.btSelectStationBoardStation.UseVisualStyleBackColor = true;
            this.btSelectStationBoardStation.Click += new System.EventHandler(this.SelectStationBoardStation_Click);
            // 
            // cbAutoRefreshStationBoard
            // 
            this.cbAutoRefreshStationBoard.AutoSize = true;
            this.cbAutoRefreshStationBoard.Location = new System.Drawing.Point(7, 54);
            this.cbAutoRefreshStationBoard.Name = "cbAutoRefreshStationBoard";
            this.cbAutoRefreshStationBoard.Size = new System.Drawing.Size(114, 17);
            this.cbAutoRefreshStationBoard.TabIndex = 2;
            this.cbAutoRefreshStationBoard.Text = "Auto-Refresh (10s)";
            this.cbAutoRefreshStationBoard.UseVisualStyleBackColor = true;
            this.cbAutoRefreshStationBoard.CheckedChanged += new System.EventHandler(this.AutoRefreshStationBoard_CheckedChanged);
            // 
            // gbMoreStationOptions
            // 
            this.gbMoreStationOptions.Controls.Add(this.label7);
            this.gbMoreStationOptions.Controls.Add(this.dtpStationBoardDate);
            this.gbMoreStationOptions.Controls.Add(this.label11);
            this.gbMoreStationOptions.Controls.Add(this.dtpStationBoardTime);
            this.gbMoreStationOptions.Location = new System.Drawing.Point(2, 95);
            this.gbMoreStationOptions.Margin = new System.Windows.Forms.Padding(2);
            this.gbMoreStationOptions.Name = "gbMoreStationOptions";
            this.gbMoreStationOptions.Padding = new System.Windows.Forms.Padding(2);
            this.gbMoreStationOptions.Size = new System.Drawing.Size(242, 114);
            this.gbMoreStationOptions.TabIndex = 12;
            this.gbMoreStationOptions.TabStop = false;
            this.gbMoreStationOptions.Text = "Mehr Optionen";
            this.gbMoreStationOptions.Visible = false;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(2, 22);
            this.label7.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(38, 13);
            this.label7.TabIndex = 4;
            this.label7.Text = "Datum";
            // 
            // dtpStationBoardDate
            // 
            this.dtpStationBoardDate.Location = new System.Drawing.Point(5, 37);
            this.dtpStationBoardDate.Margin = new System.Windows.Forms.Padding(2);
            this.dtpStationBoardDate.Name = "dtpStationBoardDate";
            this.dtpStationBoardDate.Size = new System.Drawing.Size(233, 20);
            this.dtpStationBoardDate.TabIndex = 4;
            // 
            // label11
            // 
            this.label11.AutoSize = true;
            this.label11.Location = new System.Drawing.Point(2, 72);
            this.label11.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(25, 13);
            this.label11.TabIndex = 10;
            this.label11.Text = "Zeit";
            // 
            // dtpStationBoardTime
            // 
            this.dtpStationBoardTime.CustomFormat = "HH:mm";
            this.dtpStationBoardTime.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.dtpStationBoardTime.Location = new System.Drawing.Point(5, 87);
            this.dtpStationBoardTime.Margin = new System.Windows.Forms.Padding(2);
            this.dtpStationBoardTime.Name = "dtpStationBoardTime";
            this.dtpStationBoardTime.ShowUpDown = true;
            this.dtpStationBoardTime.Size = new System.Drawing.Size(233, 20);
            this.dtpStationBoardTime.TabIndex = 5;
            // 
            // cbMoreStationBoardOptions
            // 
            this.cbMoreStationBoardOptions.AutoSize = true;
            this.cbMoreStationBoardOptions.Location = new System.Drawing.Point(7, 74);
            this.cbMoreStationBoardOptions.Margin = new System.Windows.Forms.Padding(2);
            this.cbMoreStationBoardOptions.Name = "cbMoreStationBoardOptions";
            this.cbMoreStationBoardOptions.Size = new System.Drawing.Size(142, 17);
            this.cbMoreStationBoardOptions.TabIndex = 3;
            this.cbMoreStationBoardOptions.Text = "Mehr Optionen anzeigen";
            this.cbMoreStationBoardOptions.UseVisualStyleBackColor = true;
            this.cbMoreStationBoardOptions.CheckedChanged += new System.EventHandler(this.MoreStationBoardOptions_CheckedChanged);
            // 
            // lvStationBoard
            // 
            this.lvStationBoard.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.lvStationBoard.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.columnHeader6,
            this.columnHeader7,
            this.columnHeader11});
            this.lvStationBoard.FullRowSelect = true;
            this.lvStationBoard.GridLines = true;
            this.lvStationBoard.Location = new System.Drawing.Point(248, 2);
            this.lvStationBoard.Margin = new System.Windows.Forms.Padding(2);
            this.lvStationBoard.Name = "lvStationBoard";
            this.lvStationBoard.Size = new System.Drawing.Size(643, 478);
            this.lvStationBoard.TabIndex = 7;
            this.lvStationBoard.UseCompatibleStateImageBehavior = false;
            this.lvStationBoard.View = System.Windows.Forms.View.Details;
            // 
            // columnHeader6
            // 
            this.columnHeader6.Text = "Mit";
            this.columnHeader6.Width = 150;
            // 
            // columnHeader7
            // 
            this.columnHeader7.Text = "Ab";
            this.columnHeader7.Width = 150;
            // 
            // columnHeader11
            // 
            this.columnHeader11.Text = "Richtung";
            this.columnHeader11.Width = 150;
            // 
            // btSearchStationBoard
            // 
            this.btSearchStationBoard.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.btSearchStationBoard.Enabled = false;
            this.btSearchStationBoard.Location = new System.Drawing.Point(7, 454);
            this.btSearchStationBoard.Margin = new System.Windows.Forms.Padding(2);
            this.btSearchStationBoard.Name = "btSearchStationBoard";
            this.btSearchStationBoard.Size = new System.Drawing.Size(233, 26);
            this.btSearchStationBoard.TabIndex = 6;
            this.btSearchStationBoard.Text = "Anzeigen";
            this.btSearchStationBoard.UseVisualStyleBackColor = true;
            this.btSearchStationBoard.Click += new System.EventHandler(this.SearchStationBoard_Click);
            // 
            // cbSearchStationBoard
            // 
            this.cbSearchStationBoard.FormattingEnabled = true;
            this.cbSearchStationBoard.Location = new System.Drawing.Point(7, 28);
            this.cbSearchStationBoard.Margin = new System.Windows.Forms.Padding(2);
            this.cbSearchStationBoard.Name = "cbSearchStationBoard";
            this.cbSearchStationBoard.Size = new System.Drawing.Size(207, 21);
            this.cbSearchStationBoard.TabIndex = 0;
            this.cbSearchStationBoard.DropDown += new System.EventHandler(this.LoadStationCombobox);
            this.cbSearchStationBoard.SelectedIndexChanged += new System.EventHandler(this.StationBoardDisplayButtonValidation);
            this.cbSearchStationBoard.TextChanged += new System.EventHandler(this.StationBoardDisplayButtonValidation);
            this.cbSearchStationBoard.Leave += new System.EventHandler(this.StationBoardStationSelectionCombobox_Leave);
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(7, 13);
            this.label6.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(40, 13);
            this.label6.TabIndex = 1;
            this.label6.Text = "Station";
            // 
            // tabPage3
            // 
            this.tabPage3.Controls.Add(this.cbShowStationsNear);
            this.tabPage3.Controls.Add(this.tbSearchStation);
            this.tabPage3.Controls.Add(this.groupBoxStationInformation);
            this.tabPage3.Controls.Add(this.lvStations);
            this.tabPage3.Controls.Add(this.btStationSearch);
            this.tabPage3.Controls.Add(this.label8);
            this.tabPage3.Location = new System.Drawing.Point(4, 22);
            this.tabPage3.Margin = new System.Windows.Forms.Padding(2);
            this.tabPage3.Name = "tabPage3";
            this.tabPage3.Padding = new System.Windows.Forms.Padding(2);
            this.tabPage3.Size = new System.Drawing.Size(893, 484);
            this.tabPage3.TabIndex = 3;
            this.tabPage3.Text = "Stationen";
            this.tabPage3.UseVisualStyleBackColor = true;
            // 
            // cbShowStationsNear
            // 
            this.cbShowStationsNear.Location = new System.Drawing.Point(64, 34);
            this.cbShowStationsNear.Name = "cbShowStationsNear";
            this.cbShowStationsNear.Size = new System.Drawing.Size(101, 23);
            this.cbShowStationsNear.TabIndex = 1;
            this.cbShowStationsNear.Text = "In der Nähe";
            this.cbShowStationsNear.UseVisualStyleBackColor = true;
            this.cbShowStationsNear.Click += new System.EventHandler(this.ShowStationsNear_Click);
            // 
            // tbSearchStation
            // 
            this.tbSearchStation.Location = new System.Drawing.Point(64, 11);
            this.tbSearchStation.Margin = new System.Windows.Forms.Padding(2);
            this.tbSearchStation.Name = "tbSearchStation";
            this.tbSearchStation.Size = new System.Drawing.Size(178, 20);
            this.tbSearchStation.TabIndex = 0;
            this.tbSearchStation.TextChanged += new System.EventHandler(this.SearchStation_TextChanged);
            this.tbSearchStation.KeyUp += new System.Windows.Forms.KeyEventHandler(this.SearchStation_KeyUp);
            // 
            // groupBoxStationInformation
            // 
            this.groupBoxStationInformation.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.groupBoxStationInformation.Controls.Add(this.wbStations);
            this.groupBoxStationInformation.Controls.Add(this.tbStationLatitude);
            this.groupBoxStationInformation.Controls.Add(this.tbStationLongitude);
            this.groupBoxStationInformation.Controls.Add(this.label9);
            this.groupBoxStationInformation.Location = new System.Drawing.Point(252, 13);
            this.groupBoxStationInformation.Margin = new System.Windows.Forms.Padding(2);
            this.groupBoxStationInformation.Name = "groupBoxStationInformation";
            this.groupBoxStationInformation.Padding = new System.Windows.Forms.Padding(2);
            this.groupBoxStationInformation.Size = new System.Drawing.Size(629, 460);
            this.groupBoxStationInformation.TabIndex = 9;
            this.groupBoxStationInformation.TabStop = false;
            this.groupBoxStationInformation.Text = "Stationsinformationen";
            // 
            // wbStations
            // 
            this.wbStations.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.wbStations.Location = new System.Drawing.Point(11, 44);
            this.wbStations.Margin = new System.Windows.Forms.Padding(2);
            this.wbStations.MinimumSize = new System.Drawing.Size(10, 10);
            this.wbStations.Name = "wbStations";
            this.wbStations.Size = new System.Drawing.Size(610, 404);
            this.wbStations.TabIndex = 6;
            // 
            // tbStationLatitude
            // 
            this.tbStationLatitude.Location = new System.Drawing.Point(279, 20);
            this.tbStationLatitude.Margin = new System.Windows.Forms.Padding(2);
            this.tbStationLatitude.Name = "tbStationLatitude";
            this.tbStationLatitude.ReadOnly = true;
            this.tbStationLatitude.Size = new System.Drawing.Size(130, 20);
            this.tbStationLatitude.TabIndex = 5;
            // 
            // tbStationLongitude
            // 
            this.tbStationLongitude.Location = new System.Drawing.Point(141, 20);
            this.tbStationLongitude.Margin = new System.Windows.Forms.Padding(2);
            this.tbStationLongitude.Name = "tbStationLongitude";
            this.tbStationLongitude.ReadOnly = true;
            this.tbStationLongitude.Size = new System.Drawing.Size(130, 20);
            this.tbStationLongitude.TabIndex = 4;
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.Location = new System.Drawing.Point(8, 21);
            this.label9.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(129, 13);
            this.label9.TabIndex = 0;
            this.label9.Text = "Längengrad / Breitengrad";
            // 
            // lvStations
            // 
            this.lvStations.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left)));
            this.lvStations.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.columnHeader12});
            this.lvStations.FullRowSelect = true;
            this.lvStations.Location = new System.Drawing.Point(14, 61);
            this.lvStations.Margin = new System.Windows.Forms.Padding(2);
            this.lvStations.MultiSelect = false;
            this.lvStations.Name = "lvStations";
            this.lvStations.Size = new System.Drawing.Size(231, 414);
            this.lvStations.TabIndex = 3;
            this.lvStations.UseCompatibleStateImageBehavior = false;
            this.lvStations.View = System.Windows.Forms.View.Details;
            this.lvStations.ColumnWidthChanging += new System.Windows.Forms.ColumnWidthChangingEventHandler(this.Stations_ColumnWidthChanging);
            this.lvStations.SelectedIndexChanged += new System.EventHandler(this.Stations_SelectedIndexChanged);
            // 
            // columnHeader12
            // 
            this.columnHeader12.Text = "Name";
            this.columnHeader12.Width = 450;
            // 
            // btStationSearch
            // 
            this.btStationSearch.Enabled = false;
            this.btStationSearch.Location = new System.Drawing.Point(170, 34);
            this.btStationSearch.Margin = new System.Windows.Forms.Padding(2);
            this.btStationSearch.Name = "btStationSearch";
            this.btStationSearch.Size = new System.Drawing.Size(72, 23);
            this.btStationSearch.TabIndex = 2;
            this.btStationSearch.Text = "Suchen";
            this.btStationSearch.UseVisualStyleBackColor = true;
            this.btStationSearch.Click += new System.EventHandler(this.StationSearch_Click);
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(11, 14);
            this.label8.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(40, 13);
            this.label8.TabIndex = 4;
            this.label8.Text = "Station";
            // 
            // progressBar
            // 
            this.progressBar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.progressBar.Location = new System.Drawing.Point(763, 32);
            this.progressBar.Margin = new System.Windows.Forms.Padding(2);
            this.progressBar.MarqueeAnimationSpeed = 90;
            this.progressBar.Name = "progressBar";
            this.progressBar.Size = new System.Drawing.Size(127, 23);
            this.progressBar.TabIndex = 3;
            // 
            // menuStrip1
            // 
            this.menuStrip1.ImageScalingSize = new System.Drawing.Size(32, 32);
            this.menuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.fileToolStripMenuItem,
            this.btSettingsToolStripMenuItem});
            this.menuStrip1.Location = new System.Drawing.Point(0, 0);
            this.menuStrip1.Name = "menuStrip1";
            this.menuStrip1.Size = new System.Drawing.Size(901, 24);
            this.menuStrip1.TabIndex = 1;
            this.menuStrip1.Text = "menuStrip1";
            // 
            // fileToolStripMenuItem
            // 
            this.fileToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.mailExportToolStripMenuItem,
            this.exportToolStripMenuItem});
            this.fileToolStripMenuItem.Name = "fileToolStripMenuItem";
            this.fileToolStripMenuItem.Size = new System.Drawing.Size(46, 20);
            this.fileToolStripMenuItem.Text = "Datei";
            // 
            // mailExportToolStripMenuItem
            // 
            this.mailExportToolStripMenuItem.Image = global::SwissTransport.UI.Properties.Resources.MailIcon;
            this.mailExportToolStripMenuItem.Name = "mailExportToolStripMenuItem";
            this.mailExportToolStripMenuItem.Size = new System.Drawing.Size(144, 22);
            this.mailExportToolStripMenuItem.Text = "Mail-Export...";
            this.mailExportToolStripMenuItem.Click += new System.EventHandler(this.ExportToolStripMenuItem_Click);
            // 
            // exportToolStripMenuItem
            // 
            this.exportToolStripMenuItem.Image = global::SwissTransport.UI.Properties.Resources.CloseIcon;
            this.exportToolStripMenuItem.Name = "exportToolStripMenuItem";
            this.exportToolStripMenuItem.Size = new System.Drawing.Size(144, 22);
            this.exportToolStripMenuItem.Text = "Schliessen";
            this.exportToolStripMenuItem.Click += new System.EventHandler(this.CloseApplication_Click);
            // 
            // btSettingsToolStripMenuItem
            // 
            this.btSettingsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.sMTPToolStripMenuItem});
            this.btSettingsToolStripMenuItem.Name = "btSettingsToolStripMenuItem";
            this.btSettingsToolStripMenuItem.Size = new System.Drawing.Size(90, 20);
            this.btSettingsToolStripMenuItem.Text = "Einstellungen";
            // 
            // sMTPToolStripMenuItem
            // 
            this.sMTPToolStripMenuItem.Image = global::SwissTransport.UI.Properties.Resources.SettingsIcon;
            this.sMTPToolStripMenuItem.Name = "sMTPToolStripMenuItem";
            this.sMTPToolStripMenuItem.Size = new System.Drawing.Size(105, 22);
            this.sMTPToolStripMenuItem.Text = "SMTP";
            this.sMTPToolStripMenuItem.Click += new System.EventHandler(this.SettingsToolStripMenuItem_Click);
            // 
            // lbSelectedTab
            // 
            this.lbSelectedTab.AutoSize = true;
            this.lbSelectedTab.Font = new System.Drawing.Font("Microsoft Sans Serif", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbSelectedTab.Location = new System.Drawing.Point(18, 31);
            this.lbSelectedTab.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lbSelectedTab.Name = "lbSelectedTab";
            this.lbSelectedTab.Size = new System.Drawing.Size(132, 24);
            this.lbSelectedTab.TabIndex = 4;
            this.lbSelectedTab.Text = "Verbindungen";
            // 
            // timerStationBoard
            // 
            this.timerStationBoard.Interval = 10000;
            this.timerStationBoard.Tick += new System.EventHandler(this.TimerStationBoard_Tick);
            // 
            // SwissTransportMainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(901, 577);
            this.Controls.Add(this.lbSelectedTab);
            this.Controls.Add(this.tabControl);
            this.Controls.Add(this.menuStrip1);
            this.Controls.Add(this.progressBar);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MainMenuStrip = this.menuStrip1;
            this.Margin = new System.Windows.Forms.Padding(2);
            this.MinimumSize = new System.Drawing.Size(709, 600);
            this.Name = "SwissTransportMainForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Swiss Transport - by Thomas Gassmann";
            this.Load += new System.EventHandler(this.SwissTransportMainForm_Load);
            this.tabControl.ResumeLayout(false);
            this.tabPage2.ResumeLayout(false);
            this.tabPage2.PerformLayout();
            this.gbExtendedOptions.ResumeLayout(false);
            this.gbExtendedOptions.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.tabPage1.ResumeLayout(false);
            this.tabPage1.PerformLayout();
            this.gbMoreStationOptions.ResumeLayout(false);
            this.gbMoreStationOptions.PerformLayout();
            this.tabPage3.ResumeLayout(false);
            this.tabPage3.PerformLayout();
            this.groupBoxStationInformation.ResumeLayout(false);
            this.groupBoxStationInformation.PerformLayout();
            this.menuStrip1.ResumeLayout(false);
            this.menuStrip1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.TabControl tabControl;
        private System.Windows.Forms.TabPage tabPage2;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.TabPage tabPage3;
        private System.Windows.Forms.ListView lvConnections;
        private System.Windows.Forms.ColumnHeader columnHeader1;
        private System.Windows.Forms.ColumnHeader columnHeader2;
        private System.Windows.Forms.CheckBox cbShowExtendedOptions;
        private System.Windows.Forms.GroupBox gbExtendedOptions;
        private System.Windows.Forms.ComboBox cbArrival;
        private System.Windows.Forms.ComboBox cbDeparture;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.DateTimePicker dtpConnectionSearchDate;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.RadioButton rbArrivalTime;
        private System.Windows.Forms.RadioButton rbDepartureTime;
        private System.Windows.Forms.Button btSearchConnections;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.ComboBox cbSearchStationBoard;
        private System.Windows.Forms.ProgressBar progressBar;
        private System.Windows.Forms.DateTimePicker dtpStationBoardDate;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Button btSearchStationBoard;
        private System.Windows.Forms.ColumnHeader columnHeader6;
        private System.Windows.Forms.ColumnHeader columnHeader7;
        private System.Windows.Forms.ColumnHeader columnHeader11;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Button btStationSearch;
        private System.Windows.Forms.ListView lvStations;
        private System.Windows.Forms.ColumnHeader columnHeader12;
        private System.Windows.Forms.GroupBox groupBoxStationInformation;
        private System.Windows.Forms.TextBox tbStationLatitude;
        private System.Windows.Forms.TextBox tbStationLongitude;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.WebBrowser wbStations;
        private System.Windows.Forms.DateTimePicker dtpConnectionSearchTime;
        private System.Windows.Forms.DateTimePicker dtpStationBoardTime;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.CheckBox cbMoreStationBoardOptions;
        private System.Windows.Forms.GroupBox gbMoreStationOptions;
        private System.Windows.Forms.ListView lvStationBoard;
        private System.Windows.Forms.TextBox tbSearchStation;
        private System.Windows.Forms.MenuStrip menuStrip1;
        private System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem exportToolStripMenuItem;
        private System.Windows.Forms.ColumnHeader columnHeader3;
        private System.Windows.Forms.ColumnHeader columnHeader4;
        private System.Windows.Forms.ColumnHeader columnHeader5;
        private System.Windows.Forms.ColumnHeader columnHeader13;
        private System.Windows.Forms.Label lbSelectedTab;
        private System.Windows.Forms.CheckBox cbAutoRefreshStationBoard;
        private System.Windows.Forms.Timer timerStationBoard;
        private System.Windows.Forms.Button btSelectDepartureStation;
        private System.Windows.Forms.Button btSelectArrivalStation;
        private System.Windows.Forms.Button btSelectStationBoardStation;
        private System.Windows.Forms.Button cbShowStationsNear;
        private System.Windows.Forms.ToolStripMenuItem mailExportToolStripMenuItem;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.ToolStripMenuItem btSettingsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem sMTPToolStripMenuItem;
    }
}

